//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRestfulAPI.RestApi.v1.Users.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existing_databases
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
